"""initial schema

Revision ID: dbe3c105925e
Revises:
Create Date: 2026-07-09 17:13:26.657329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbe3c105925e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_user_level", sa.String(length=120), nullable=True),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learning_paths_slug"), "learning_paths", ["slug"], unique=True)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum("concept", "company", "format", "skill", "formula", name="tag_category"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_category"), "tags", ["category"], unique=False)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_topic_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["parent_topic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_parent_topic_id"), "topics", ["parent_topic_id"], unique=False)
    op.create_index(op.f("ix_topics_slug"), "topics", ["slug"], unique=True)
    op.create_table(
        "concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("intuition", sa.Text(), nullable=True),
        sa.Column("common_mistakes", sa.Text(), nullable=True),
        sa.Column("interview_tips", sa.Text(), nullable=True),
        sa.Column("prerequisites", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concepts_slug"), "concepts", ["slug"], unique=True)
    op.create_index(op.f("ix_concepts_topic_id"), "concepts", ["topic_id"], unique=False)
    op.create_table(
        "flashcards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", "expert", name="difficulty"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flashcards_topic_id"), "flashcards", ["topic_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("canonical_solution", sa.Text(), nullable=True),
        sa.Column("short_answer", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", "expert", name="difficulty"),
            nullable=False,
        ),
        sa.Column("estimated_time_seconds", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_title", sa.String(length=300), nullable=True),
        sa.Column("source_license", sa.String(length=120), nullable=True),
        sa.Column("extraction_method", sa.String(length=120), nullable=True),
        sa.Column("model_version", sa.String(length=120), nullable=True),
        sa.Column("generated_from_id", sa.Integer(), nullable=True),
        sa.Column("source_attribution", sa.Text(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("subtopic_id", sa.Integer(), nullable=True),
        sa.Column("company_hint", sa.String(length=200), nullable=True),
        sa.Column("frequency_score", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("expected_solution_pattern", sa.Text(), nullable=True),
        sa.Column("common_mistakes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prerequisites", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_question_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "approved", "rejected", name="content_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["generated_from_id"], ["questions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subtopic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_difficulty"), "questions", ["difficulty"], unique=False)
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_index(op.f("ix_questions_subtopic_id"), "questions", ["subtopic_id"], unique=False)
    op.create_index(op.f("ix_questions_topic_id"), "questions", ["topic_id"], unique=False)
    op.create_table(
        "user_topic_mastery",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "topic_id"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempts_question_id"), "attempts", ["question_id"], unique=False)
    op.create_index(op.f("ix_attempts_user_id"), "attempts", ["user_id"], unique=False)
    op.create_table(
        "concept_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_concept_id", sa.Integer(), nullable=False),
        sa.Column("target_concept_id", sa.Integer(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum("requires", "related_to", "used_in", name="concept_edge_relationship_type"),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["source_concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_concept_id",
            "target_concept_id",
            "relationship_type",
            name="uq_concept_edges_source_target_relationship",
        ),
    )
    op.create_index(
        op.f("ix_concept_edges_relationship_type"),
        "concept_edges",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_edges_source_concept_id"),
        "concept_edges",
        ["source_concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_edges_target_concept_id"),
        "concept_edges",
        ["target_concept_id"],
        unique=False,
    )
    op.create_table(
        "learning_path_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learning_path_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("required_mastery_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learning_path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "learning_path_id", "order_index", name="uq_learning_path_steps_path_order"
        ),
    )
    op.create_index(
        op.f("ix_learning_path_steps_concept_id"),
        "learning_path_steps",
        ["concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_path_steps_learning_path_id"),
        "learning_path_steps",
        ["learning_path_id"],
        unique=False,
    )
    op.create_table(
        "question_tags",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id", "tag_id"),
    )
    op.create_index(op.f("ix_question_tags_tag_id"), "question_tags", ["tag_id"], unique=False)

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_ts_config WHERE cfgname = 'quant_prep_english'
            ) THEN
                CREATE TEXT SEARCH CONFIGURATION quant_prep_english (
                    COPY = pg_catalog.english
                );
            END IF;
        END
        $$;
        """
    )
    op.create_index(
        "ix_topics_parent_topic_id_order_index",
        "topics",
        ["parent_topic_id", "order_index"],
    )
    op.execute(
        """
        CREATE INDEX ix_questions_fts ON questions USING gin (
            to_tsvector(
                'quant_prep_english',
                coalesce(title, '') || ' ' || coalesce(body, '')
            )
        )
        """
    )
    op.execute(
        """
        CREATE INDEX ix_concepts_fts ON concepts USING gin (
            to_tsvector(
                'quant_prep_english',
                coalesce(name, '') || ' ' ||
                coalesce(definition, '') || ' ' ||
                coalesce(formula, '')
            )
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_concepts_fts")
    op.execute("DROP INDEX IF EXISTS ix_questions_fts")
    op.drop_index("ix_topics_parent_topic_id_order_index", table_name="topics")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_tags_tag_id"), table_name="question_tags")
    op.drop_table("question_tags")
    op.drop_index(op.f("ix_learning_path_steps_learning_path_id"), table_name="learning_path_steps")
    op.drop_index(op.f("ix_learning_path_steps_concept_id"), table_name="learning_path_steps")
    op.drop_table("learning_path_steps")
    op.drop_index(op.f("ix_concept_edges_target_concept_id"), table_name="concept_edges")
    op.drop_index(op.f("ix_concept_edges_source_concept_id"), table_name="concept_edges")
    op.drop_index(op.f("ix_concept_edges_relationship_type"), table_name="concept_edges")
    op.drop_table("concept_edges")
    op.drop_index(op.f("ix_attempts_user_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_question_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("user_topic_mastery")
    op.drop_index(op.f("ix_questions_topic_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_subtopic_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_difficulty"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_flashcards_topic_id"), table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_index(op.f("ix_concepts_topic_id"), table_name="concepts")
    op.drop_index(op.f("ix_concepts_slug"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_index(op.f("ix_topics_slug"), table_name="topics")
    op.drop_index(op.f("ix_topics_parent_topic_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_category"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_learning_paths_slug"), table_name="learning_paths")
    op.drop_table("learning_paths")
    sa.Enum(name="concept_edge_relationship_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="content_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="difficulty").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tag_category").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
